# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  webapi:
    image: rocchini/sample-api:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks: 
      - sampleapinetwork
    depends_on: 
      - "sqldatabase"

  sqldatabase:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "teste@123"
        ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433
    networks: 
      - sampleapinetwork

networks: 
  sampleapinetwork:
    driver: bridge
